"""empty message

Revision ID: 157fe692367e
Revises: 29d499553de3
Create Date: 2015-03-28 11:07:42.314483

"""

# revision identifiers, used by Alembic.
revision = '157fe692367e'
down_revision = '29d499553de3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('task_id', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'task_id')
    ### end Alembic commands ###
