"""empty message

Revision ID: 17fa4624585
Revises: 551ba562ce44
Create Date: 2015-03-11 00:03:19.301176

"""

# revision identifiers, used by Alembic.
revision = '17fa4624585'
down_revision = '551ba562ce44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
