"""empty message

Revision ID: 29d499553de3
Revises: 4b5f6069c5df
Create Date: 2015-03-11 10:34:38.801595

"""

# revision identifiers, used by Alembic.
revision = '29d499553de3'
down_revision = '4b5f6069c5df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
