"""Add Password column

Revision ID: 2c9095ddc336
Revises: 792da119ed8
Create Date: 2015-05-18 14:05:38.055846

"""

# revision identifiers, used by Alembic.
revision = '2c9095ddc336'
down_revision = '792da119ed8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digest_key', sa.String(length=64), nullable=True),
    sa.Column('salt', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password')
    ### end Alembic commands ###
