"""empty message

Revision ID: 4322fa32da22
Revises: 1871b0bae8bf
Create Date: 2015-03-10 23:20:55.850627

"""

# revision identifiers, used by Alembic.
revision = '4322fa32da22'
down_revision = '1871b0bae8bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
