"""empty message

Revision ID: 551ba562ce44
Revises: 4322fa32da22
Create Date: 2015-03-11 00:03:11.173695

"""

# revision identifiers, used by Alembic.
revision = '551ba562ce44'
down_revision = '4322fa32da22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
