"""empty message

Revision ID: 792da119ed8
Revises: 157fe692367e
Create Date: 2015-04-10 01:40:35.021908

"""

# revision identifiers, used by Alembic.
revision = '792da119ed8'
down_revision = '157fe692367e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('type_code', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'type_code')
    ### end Alembic commands ###
