"""Add orphams column to Database

Revision ID: 84d612180d2
Revises: 2c9095ddc336
Create Date: 2015-05-18 16:39:51.168546

"""

# revision identifiers, used by Alembic.
revision = '84d612180d2'
down_revision = '2c9095ddc336'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database', sa.Column('number_of_orphams', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('database', 'number_of_orphams')
    ### end Alembic commands ###
