from debian:wheezy

maintainer jglamine@gmail.com

# copy conserved domain database
ADD Cdd/Cdd.rps /Cdd/Cdd.rps
ADD Cdd/Cdd.freq /Cdd/Cdd.freq
ADD Cdd/Cdd.loo /Cdd/Cdd.loo
ADD Cdd/Cdd.aux Cdd/Cdd.phr Cdd/Cdd.pin Cdd/Cdd.psd Cdd/Cdd.psi Cdd/Cdd.psq /Cdd/
